# Generated by Django 5.2.7 on 2025-10-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ca",
            options={
                "verbose_name": "Certification Authority",
                "verbose_name_plural": "Certification Authorities",
            },
        ),
        migrations.AlterModelOptions(
            name="personnel",
            options={"verbose_name": "Personnel", "verbose_name_plural": "Personnel"},
        ),
        migrations.RemoveField(
            model_name="ca",
            name="hmac_secret",
        ),
        migrations.AddField(
            model_name="certificate",
            name="signature",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="position",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
