# Generated by Django 5.2.7 on 2025-10-22 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_ca_options_alter_personnel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="certificate",
        ),
    ]
