# Generated by Django 5.2.7 on 2025-10-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_certificate_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicKeyRegistery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Public Key Registery",
                "verbose_name_plural": "Public Key Registery",
            },
        ),
    ]
